### ISSUE TITLE
Making twgit ignoring all feature-, demo-, hotfix- and release- prefixes on command launch

### ISSUE THREAD

**Issue by Sebastien-Hanicotte** [Twenga/twgit#114]
When regularly switching between git and twgit commands, you'll at least one time raised the problem of writing down complete tag name when dealing with twgit instead of only the identifier of the feature / demo / release / hotfix.

It would be interesting to automaticaly suppress those 'prefixes' when accidentaly using them.

(Issue based on Gaubry's idea)

**Comment by geoffroy-aubry** [comment]
And 'v-' prefix for tags…

**Comment by Sebastien-Hanicotte** [comment]
Sorry for the "duplicate", I didn't see and reming there was once an issue written for such feature :)

**Comment by geoffroy-aubry** [comment]
sha: 2675ae3aa48c88542a6ef36a67241a10efa8baeb
