### ISSUE TITLE
Making dyslexia a lesser work-disorder

### ISSUE THREAD

**Issue by Sebastien-Hanicotte** [Twenga/twgit#117]
Sometimes, when fingers runs faster than mind (or else), you end up writing down all the letters of a command, but not in the good order.

Because dyslexia happens, we sure can deal with that problem on commonly used commands.

**Comment by Sebastien-Hanicotte** [comment]
The feature finally passed all the test written... but this feature may need some more tests to ensure guess works its way with some randomly characters' shaken commands and actions.

**Comment by geoffroy-aubry** [comment]
_Should_ be OK on BSD : [fold command](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/fold.1.html) :-)

Anyone to test on BSD ?

**Comment by Sebastien-Hanicotte** [comment]
```
echo 'feature' | fold -w1 | sort | uniq -c | tr -d '[:space:]\n' 
```

:+1:  Tested under system running OS X
