### ISSUE TITLE
Tag information in a dedicated file

### ISSUE THREAD

**Issue by Sebastien-Hanicotte** [Twenga/twgit#118]
CVS projects had their $id:$ keyword to retrieve current deployment tag
SVN projects had their $id$ keyword to retrieve this same information
Git... does not have this kind of feature.

Assurely, Twgit can help Git Users to update this information and allow projects who needs to access this kind of information to retrieve it easily.

The .twgit config file will ask for a particular file where to put the current Tag name, if left blank, then the file will not be created, but if filled with Complete_Path, this information will be retrieved and stored in each Tag created with Twgit process.

Let's hope it will be useful for a lot of projects, which will be able to inform their users their version info.

based on @gletournel and @geoffroy-aubry original idea (Let's give credit where credit is due)

**Comment by geoffroy-aubry** [comment]
4b810d5
