### ISSUE TITLE
Add command twgit feature pull

### ISSUE THREAD

**Issue by chemidy** [Twenga/twgit#122]
It's very weird to mix twgit and git command for new user of twgit. So, it's very usefull to have all needed command by using twgit.

I will add a command twgit feature pull , this is a shortcut of git fetch --prune origin and git merge origin/feature-MY_CURRENT_FEATURE or git pull origin it's the same

Of course i will add this command for all branches : release / demo / hotfix / ....

**Comment by ltoussaint** [comment]
Included in #149
