### ISSUE TITLE
Allow Twgit working with zsh 

### ISSUE THREAD

**Issue by morith** [Twenga/twgit#127]

**Comment by geoffroy-aubry** [comment]
Hello Morith :-)
It's a huge request !
I can help you for the development of this issue… but I will don't make this development :p

**Comment by rderocle** [comment]
Main problem is completion that's not working. I'm on it.
Morith, did you identify other problems ? I'm a zsh user and besides completion, everything is working fine for me.

**Comment by morith** [comment]
Hello,

Everything is working for me too, except the completion.

I have to do more tests.

**Comment by rderocle** [comment]
Okay. I finished a first version of completion. I have to modify the install script because it's not the same way to install completion on zsh.

**Comment by rderocle** [comment]
Okay I have a full working version. Need review :)

**Comment by geoffroy-aubry** [comment]
great feature :-)

**Comment by rderocle** [comment]
thanks @geoffroy-aubry. did you review it ? :D

**Comment by geoffroy-aubry** [comment]
Yes, I did it => label "ready to release" added.
I merged it into current release, just before you add new commits :/

**Comment by rderocle** [comment]
okay, sorry. no further commits so you can merge again =)
