### ISSUE TITLE
Migrate install script in bash

### ISSUE THREAD

**Issue by ltoussaint** [Twenga/twgit#131]
To install twgit, we need to have make command installed on the server.

As twgit works with bash, it could be a good idea to migrate install script in bash.

With this solution, only bash >= v4 will be mandatory to use twgit.

**Comment by rderocle** [comment]
makefile has been migrated to makefile.sh in https://github.com/Twenga/twgit/issues/127 :)

**Comment by geoffroy-aubry** [comment]
Issue to close?

**Comment by rderocle** [comment]
@Latouss take a look in the new implementation and tell us if that's what you wanted :)

**Comment by ltoussaint** [comment]
It's ok.
I close the issue
