### ISSUE TITLE
Use environment bash path

### ISSUE THREAD

**Issue by morith** [Twenga/twgit#132]
Hello,

Bash binary is located elsewhere on my computer.

Can we change the shebang of each scripts with this one ?

``` bash
#!/usr/bin/env bash
```

I saw that the changes were done in this commit : https://github.com/Twenga/twgit/commit/a9ad5571a83df69d978fafd66f0bfedd63f661b0

**Comment by rderocle** [comment]
I'm waiting for my PR to be reviwed and my commit to be merged =)

**Comment by geoffroy-aubry** [comment]
Hello Morith,
This problem is corrected in current release. Thx Romain :-)
