### ISSUE TITLE
Fix user home detection

### ISSUE THREAD

**Issue by rderocle** [Twenga/twgit#141]
When the install is itself included in another script, the user home detection fails and we lose the user information.
We have to use logname instead.
The same problem comes when we want to clean.
- [x] Change user home detection

~~Add "sudo" in front of clean command (in _install_executable_ function)~~
~~Add "sudo" in front of link command (in _install_executable_ function)~~

**Comment by rderocle** [comment]
Bon après investigation, le problème du sudo venait d'ailleurs. je rollback

**Comment by geoffroy-aubry** [comment]
Le détecter avant git push eût été l'idéal ;-)

**Comment by rderocle** [comment]
c'est pour ça qu'on utilise des branches, pour rollback easy !

Romain DEROCLE
rderocle@gmail.com
tel. 06 75 28 74 57
