### ISSUE TITLE
Curl as failover of wget for connectors

### ISSUE THREAD

**Issue by ltoussaint** [Twenga/twgit#146]
OSX does not have wget installed by default.
Allow connectors to use curl as failover.

**Comment by geoffroy-aubry** [comment]
Don't forget to mention new Gitlab connector in README/CHANGELOG because no feature was dedicated.

**Comment by geoffroy-aubry** [comment]
Do python version of gitlab connector is working?

**Comment by ltoussaint** [comment]
This connector only work with PHP.
With python it will return an empty string.

**Comment by geoffroy-aubry** [comment]
OK. Hmm… so why give priority to pyhton language in `feature_subject_gitlab.sh`, line 49?
It wouldn't be better if python version doesn't work to simply remove it and throw an error?

**Comment by ltoussaint** [comment]
The chosen language always was PHP if installed.
So the code with python was never call.

But to be compatible with the most OS, I did the python version.
So it should be ok now.

**Comment by geoffroy-aubry** [comment]
_"The chosen language always was PHP if installed."_: sorry, but the code below seems say the opposite. Currently, in each connector, the chosen language is PHP if and only if Python is not installed. ^^

But if your Python version is working, it's fine :-)

``` bash
# Python or PHP ?
language='?'
which python 1>/dev/null 2>&1
if [ $? -eq 0 ]; then
    language='python'
else
    which php 1>/dev/null 2>&1
    if [ $? -eq 0 ]; then
        language='php'
    fi
fi
```

**Comment by ltoussaint** [comment]
Yes, this code was added when I did the python version ;-)

**Comment by geoffroy-aubry** [comment]
OK, thx
