### ISSUE TITLE
Add demo/test branches for marketing teams or other needs

### ISSUE THREAD

**Issue by geoffroy-aubry** [Twenga/twgit#71]

**Comment by carontony** [comment]
Vous avez ce besoin chez Hi-media?
Je ne me souviens plus très bien pourquoi nous avions besoin de cette fonctionnalité chez Twenga.

**Comment by geoffroy-aubry** [comment]
Le besoin Hi-media, et autant que je me souvienne celui aussi chez Twenga, était de pouvoir présenter l'assemblage de plusieurs `features` à une équipe marketing, une démo. Cet assemblage n'est pas forcément celui en cours d'intégration sur la `release`. Il y a bien la solution qui consisterait à créer une `feature-demo`, mais ce n'est pas très propre, cela dévoie un peu le workflow.

**Comment by mrsinham** [comment]
Il peut même y avoir besoin d'une branche projet, par exemple project-xxxx ou on merge en attendant de releaser le projet d'un coup ?

**Comment by geoffroy-aubry** [comment]
Je ne suis pas sûr de comprendre le besoin, pourquoi ne pas ouvrir tout de suite la release et commencer à y merger les features ?
Par ailleurs pour garder le workflow le plus simple possible, peut-être peut-on envisager un nom commun (les appeler de la même façon) aux branches demo-xxxx et project-xxxx (si ces dernières se font vraiment nécessaires)…

**Comment by mrsinham** [comment]
Nous avons eu le cas à Twenga, ou un projet a dépassé le stade de livraison de la release courante (gros projet, et les release / hotfix ont continué a evoluer pendant ce temps la). Du coup nous avons du créer une branche temporaire permettant de merger au fur et a mesure notre projet qui lui est composé de plein de petits tickets. Il aurait été apprecié en plus d'avoir une commande qui ramene automatiquement l'evolution des stables sur le projet courant.

**Comment by mrsinham** [comment]
Des nouvelle sur le sujet ? :) Merci !

**Comment by geoffroy-aubry** [comment]
Cyrille a commencé le travail, ça fleure bon ^^
Peut-être nous en dira-t-il plus ici ?

**Comment by mrsinham** [comment]
Une très bonne nouvelle!

**Comment by chemidy** [comment]
Hello.

J'ai commencé la gestion de branche de demo/integration/qa/le_nom_qui_va_bien

Pour l'instant je suis parti sur le concept du besoin de plusieurs branches d’intégration

L'idée est de pouvoir créer une branche de demo et on merge des features.

=> twgit demo start NUMERO_DE_TICKET_DEMO

------> Equivalent a un twgit feature start, se base sur la dernière stable et prefix la branche avec un PREFIX defini dans la conf twgit

=> twgit demo remove NUMERO_DE_TICKET_DEMO

------> Equivalent a un twgit feature remove

=> twgit demo merge NUMERO_DE_FEATURE

------> Equivalent a un git merge origin/NUMERO_DE_FEATURE

------> Petite question, est ce que le push origin est intégré a la fin du demo merge, ou alors on indique comme lorsque l'on modifie une feature via des commit, qu'il faut faire un push origin en rajoutant une commande demo status ?

=> twgit demo list 
git# git fetch --prune origin

(i) Remote demos in progress:
Demo: origin/demo-123456 Demonstration de Noel
    - origin/feature-40407 [merged] Récupération de ma feature de noel
    - origin/feature-47326 [merged] Fwd: Echeance XYZ

Demo: origin/demo-43872 Ticket integration twgit
    -  [no features merged] 

A venir

=> twgit demo build <env>

----> Commande qui permet d'executer un script shell, pour par exemple générer le livrable de la demo (.deb, tar.gz, ...)

=> twgit demo merge-into-release 

----> intégrer les features de la demo dans la release en cours

Si vous avez des suggestions / questions n'hésitez pas

**Comment by geoffroy-aubry** [comment]
Hors mécanique et seulement sur le plan « ergonomie », faudra peut-être unifier les comportements des actions suivantes : `twgit demo merge <featurename>` et `twgit feature merge-into-release <releasename>` qui ont des approches opposées… => soit tout passer en approche `merge-into-(release|demo)`, soit tout passer en approche `(release|demo) merge`…

**Comment by geoffroy-aubry** [comment]
La commande `twgit demo build` me gêne un peu. Ton idée de proposer des triggers, comme sur release finish par exemple, me plaît d'avantage, et est plutôt neutre. Mais twgit n'est pas un outil de déploiement…

**Comment by chemidy** [comment]
OK pour la commande twgit demo build, je la sors de la feature.

Pour ce qui est de la commande merge, je vais garder le fonctionnement actuel. a savoir twgit demo merge <feature_name>, car autant pour le merge-into-release c'est faisable car il n'y a qu'une release en cours, pour les demo on peut en avoir plusieurs donc il faudrait passer plusieurs arguments c'est pas super.
