### ISSUE TITLE
 Should "hotfix remove" create a tag on stable branch?

### ISSUE THREAD

**Issue by nassimseddiki** [Twenga/twgit#72]
We've mistakenly created a hotfix on our project. Doing a "hotfix remove" created a tag on our stable branch. That means our next hotfix version number will be incremented thus creating a gap between two hotfixes.

Here is the log (we just removed the sensitive parts) : 

``` bash
twgit hotfix remove 4.65.2
Check valid ref name...
Check clean working tree...
Check current branch...
git# git fetch --prune origin
Check valid ref name...
Check valid tag name...
Check whether tag '4.65.2' already exists...
git# git checkout stable
Switched to branch 'stable'
git# git merge origin/stable
Already up-to-date.
git# git branch -D hotfix-4.65.2
Deleted branch hotfix-4.65.2 (was ca2a5d6).
git# git push origin :hotfix-4.65.2
=> Syncing Gitorious... [OK]
 - [deleted]         hotfix-4.65.2
git# git tag -a v4.65.2 -m "[twgit] Hotfix remove: hotfix-4.65.2"
git# git push --tags origin stable
=> Syncing Gitorious... [OK]
 * [new tag]         v4.65.2 -> v4.65.2
```

Should the hotfix remove command create a tag? It could just be removed so the same version number could be used again for a relevant fix.

**Comment by geoffroy-aubry** [comment]
Both commands `$twgit hotfix remove` and `$twgit release remove` create a tag. That is intentionally to avoid problems if other developpers have pulled the deleted branch. So future new release and new hotfix are really new, without any same named branches in any developper's repository.

**Comment by nassimseddiki** [comment]
Ok that makes sense :) We'll just have to aware that some version numbers (for removed hotfixes) may exist with no commit in them.
