### ISSUE TITLE
Update of twgit cancel the first called functionnality

### ISSUE THREAD

**Issue by Sebastien-Hanicotte** [Twenga/twgit#74]
When calling any twgit command, Twgit checks periodicaly (seems to be each 2 days by default) if there is not a new version of itself.

If it finds one update available, it invites you to choose between continuing the execution of your command or updating to a new version of Twgit.

By choosing the update way, when the update is finished, it returns to the command prompt. A short message inviting you to "re-entering your request".

> Next auto-update check in 2 days.
> Thank you for re-entering your request.

Won't it be easier to perform the update, then executing the command which was at first called ?

**Comment by geoffroy-aubry** [comment]
Indeed :-)
