### ISSUE TITLE
grep -P doesn't work with Mac OS Mountain Lion

### ISSUE THREAD

**Issue by ltoussaint** [Twenga/twgit#78]
Option -P for "grep" command doesn't work on Mountain Lion OS.

Mountain Lion doesn't use GNU grep  but BSD grep which does not implement -P option.

**Comment by geoffroy-aubry** [comment]
Arghhhh, « Perl Regex Removed From Grep in Mountain Lion », http://www.dirtdon.com/?p=1452

**Comment by geoffroy-aubry** [comment]
Compatibility updated: Mac OS X 10.7 (Lion) or lower…
