### ISSUE TITLE
Allow to parameter the default rendering of twgit feature list and the like 

### ISSUE THREAD

**Issue by geoffroy-aubry** [Twenga/twgit#84]
For example, set `-c` as a default parameter…

**Comment by chemidy** [comment]
Add new parameter : TWGIT_DEFAULT_RENDERING_OPTION

You can choose defaul rendering in this list ('','c','x'), '' => Verbose, c => compact, x => eXtremely compact

Only a simple change in the function process_options used everywhere, i add the value of TWGIT_DEFAULT_RENDERING_OPTION parameter in FCT_OPTIONS.

Enjoy.

**Comment by geoffroy-aubry** [comment]
Hello, if you add `#<issue>` in commit messages, then related commits appear here (as with Redmine) ^^

**Comment by geoffroy-aubry** [comment]
Thank you for commit :-)
But `process_options()` function was a unit tested function. You see that with `@testedby` annotation. Please do not push any commit with improper `@testedby` annotation.

All the code uses 4 spaces for indentation level. Please repsect this: `inc/options_handler.inc.sh:70`

Having said this, i am grateful for your commits :-)
